name: Pull Request Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out base branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}

      - name: Check out head branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          path: head

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install lxml

      - name: Run validation script
        run: python .github/workflows/validate_pr.py
